### ISSUE TITLE
加入周数及日期显示

### ISSUE THREAD

**Issue by kqwyf** [YZune/WakeupSchedule_Kotlin#1]
希望在APP中左右翻页时显示当前页面是第X周，X月X日。
该功能有助于对照课表查看未来某活动是否撞课等。

**Comment by YZune** [comment]
这个我的设计，是在开学之后再显示哒。按理来说现在已经显示周数了，对吗？

**Comment by kqwyf** [comment]
是的，抱歉没有充分使用就提Issue
