### ISSUE TITLE
课表设置中学期开始时间，设置的时间被显示到了上课时间

### ISSUE THREAD

**Issue by mr-cn** [YZune/WakeupSchedule_Kotlin#18]
版本：Google play 3.576

![Screenshot_2019-12-16-13-56-07-156_com suda yzune wakeupschedule pro](https://user-images.githubusercontent.com/19818121/70882860-0b546c80-200c-11ea-97a1-0c5a3172629b.png)

可以看到上课时间是2019-2-4，但是实际上是刚刚点击学期开始时间设置的日期。只是显示问题，退出后再进入可以看到修改是成功的。

---

然后我校长沙理工大学的课表解析有问题。
![Screenshot_2019-12-16-13-56-15-943_com suda yzune wakeupschedule pro](https://user-images.githubusercontent.com/19818121/70882979-74d47b00-200c-11ea-90f2-08e36a301f6d.png)

除去HTML的问题，第五节实际应为5-6节，往后顺延。(没发现长理的解析相关代码，是没有push上来吗)

**Comment by YZune** [comment]
最新版本是否解决了这些问题呢

**Comment by mr-cn** [comment]
嗯嗯，都解决了

https://github.com/YZune/WakeupSchedule_Kotlin/blob/a69fb7555e0917e0ba8a0dadbf3248364666b089/app/src/main/java/com/suda/yzune/wakeupschedule/schedule_import/parser/qz/QzBrParser.kt#L6
解析的问题，应该是加个 `.substringBefore("<span>")`就好了，当时都准备提pr了，结果后来忘了。。

新版本UI很好看，作者辛苦啦
