### ISSUE TITLE
同一时间段非本周课程的显示和设置问题

### ISSUE THREAD

**Issue by Spico197** [YZune/WakeupSchedule_Kotlin#2]
同一时间段非本周课程在app中会重叠显示。此时若点击该课程区域，只能点开一个。需要切换为不现实非本周课程才能解决。不知道下一个版本能否修复一下这个问题。超级课程表的卡片切换或许是一种解决方案。

**Comment by YZune** [comment]
嗯嗯好的，谢谢反馈

**Comment by YZune** [comment]
已解决
