### ISSUE TITLE
请求删除暨南大学的课程导入

### ISSUE THREAD

**Issue by Jiuh-star** [YZune/WakeupSchedule_Kotlin#39]
学校近期使用了新的教务系统（还是定制的o(╥﹏╥)o），旧教务系统已经不再更新，因此原有的课程导入无法导入最新的课程，新课程导入有些复杂，这两天研究研究_(:з」∠)_

**Comment by Jiuh-star** [comment]
另外，@YZune GitHub上的代码已经好久没更新了:-(

**Comment by YZune** [comment]
好的好的，辛苦了

**Comment by Jiuh-star** [comment]
好了没有我什么事了，新教务系统是金智教务:joy:

**Comment by Jiuh-star** [comment]
学校教务课表地址是：https://jw.jnu.edu.cn/jwapp/sys/wdkb/*default/index.do

**Comment by YZune** [comment]
403 Forbidden😂是只能校园网访问吗

**Comment by YZune** [comment]
我找到校外访问的地址啦，我用那个吧

**Comment by Jiuh-star** [comment]
啊啊好的:joy:，课表地址也可以用：https://jw.jnu.edu.cn/jwapp/sys/wdkb/*default/index.do#/xskcb，但也是校园网才能访问，大大辛苦啦！
