### ISSUE TITLE
English Version

### ISSUE THREAD

**Issue by hungvu193** [YZune/WakeupSchedule_Kotlin#4]
Great Job, but i don't really understand the follow of app,  can you add english version for this application, i think it's very useful :+1:

**Comment by YZune** [comment]
OK. I am planning to add English version for it later. Thank you for using it.

**Comment by YZune** [comment]
> Great Job, but i don't really understand the follow of app, can you add english version for this application, i think it's very useful 👍

OK. I am planning to add English version for it later. Thank you for using it.

**Comment by YZune** [comment]
OK. I am planning to add English version for it later. Thank you for using it.

**Comment by hungvu193** [comment]
You can put your text in string.xml and i can help you translate it xD.
