### ISSUE TITLE
当课程信息的某个字段含有空格时，导入内容错误

### ISSUE THREAD

**Issue by LilligantMatsuri** [YZune/WakeupSchedule_Kotlin#5]
> 版本号：3.25（酷安应用市场）
> 教务系统类型：正方

假设有这样一节课程，教师是外教（姓名中含有空格）：
![example](https://user-images.githubusercontent.com/26195226/48669114-35e9a280-eb38-11e8-8af1-a287326e811e.png)
则导入的结果如下图所示：
![info](https://user-images.githubusercontent.com/26195226/48669143-fcfdfd80-eb38-11e8-94cc-2083e9491e97.png)
空格后的内容被误判为上课地点，填入了下一栏

我认为问题可能出在这一段：[ImportViewModel.kt#L179](https://github.com/YZune/WakeupSchedule_Kotlin/blob/e835fef02834c7d8eff499c4307bd0d85f0a443f/app/src/main/java/com/suda/yzune/wakeupschedule/schedule_import/ImportViewModel.kt#L179)

```kt
val split = source.split(" ".toRegex()).dropLastWhile { it.isEmpty() }.toTypedArray()
```
根据教务系统的网页源码，两个字段之间是用换行符 `<br>` 进行分隔的
如果以换行符作为判断字段结束的标志，是否就可以避免这个问题呢？
之前使用过的*课程格子*没有出现这个问题，不清楚它是怎样实现的

我不懂代码，仅供参考，不当之处请指出> <

**Comment by YZune** [comment]
主要是方正教务我是利用{}这对括号来标记时间的位置的。
因为正方教务不同学校的课表形式也不太一样，但看起来都有大括号来说明时间，然后一般时间后一个是教师，再后一个是教室，之间用空格分隔，所以会导致这样的问题。
我之前没有想过会出现这种情况，谢谢提醒啦。

**Comment by YZune** [comment]
刚刚的commit已经解决这个问题啦

**Comment by LilligantMatsuri** [comment]
辛苦了：）
