### ISSUE TITLE
可以编译通过，也可以打包。但是代码里就是找不到id报紅，不知道怎么解决

### ISSUE THREAD

**Issue by yudigege** [YZune/WakeupSchedule_Kotlin#8]

**Comment by YZune** [comment]
可以具体到哪个 id 吗？或者截个图，有可能是 AS 的问题吧，我有时候也遇到过，不管它就好了。

**Comment by yudigege** [comment]
![default](https://user-images.githubusercontent.com/23008520/52765234-3f62a800-305e-11e9-8788-e0c3f28a0975.png)
就是这样运行啥的都没问题，clean rebuild和清除缓存重启都不好使

**Comment by yudigege** [comment]
gradle里面报这个错误 API 'variant.getExternalNativeBuildTasks()' is obsolete and has been replaced with 'variant.getExternalNativeBuildProviders()'.
It will be removed at the end of 2019.
getExternalNativeBuildTasks()这个过时了，应替换成这个getExternalNativeBuildProviders()，在哪里替换呀

**Comment by YZune** [comment]
这应该是一个第三方库引起的
