### ISSUE TITLE
Feature request: add background to widget

### ISSUE THREAD

**Issue by balthild** [YZune/WakeupSchedule_Kotlin#9]
![Screenshot_20190324-154021](https://user-images.githubusercontent.com/2662758/54876452-36c67400-4e4b-11e9-9898-dc7d0ccae95d.png)

A translucent background will improve the readability of the widget laying on a color-rich wallpaper.

**Comment by balthild** [comment]
It's good too to to drop some slight shadows. For example:

![_20190324_155757](https://user-images.githubusercontent.com/2662758/54876598-9d4c9180-4e4d-11e9-886e-d67ee037130c.JPG)

**Comment by YZune** [comment]
![image](https://user-images.githubusercontent.com/22848999/57304984-e06b7700-7112-11e9-9f24-12b583f3cf9e.png)

**Comment by balthild** [comment]
Great! But what I actually meant a borderless, colourless and translucent background like this image:

![image](https://user-images.githubusercontent.com/2662758/57309704-1d3b6c00-711b-11e9-9613-2bab60b9d051.png)

Of course, it would be quite perfect if you can implement text shadows.

**Comment by YZune** [comment]
Thanks for the advice. I will try.
